/**
 * Countries by continent for product market availability (ISO 3166-1 alpha-2).
 * Used in admin product edit "Markets" section.
 */
export type CountryEntry = { code: string; name: string };
export type ContinentEntry = { continent: string; countries: CountryEntry[] };

export const COUNTRIES_BY_CONTINENT: ContinentEntry[] = [
  {
    continent: "North America",
    countries: [
      { code: "US", name: "United States" },
      { code: "CA", name: "Canada" },
      { code: "MX", name: "Mexico" },
      { code: "GT", name: "Guatemala" },
      { code: "CU", name: "Cuba" },
      { code: "HT", name: "Haiti" },
      { code: "DO", name: "Dominican Republic" },
      { code: "HN", name: "Honduras" },
      { code: "NI", name: "Nicaragua" },
      { code: "SV", name: "El Salvador" },
      { code: "CR", name: "Costa Rica" },
      { code: "PA", name: "Panama" },
      { code: "JM", name: "Jamaica" },
      { code: "TT", name: "Trinidad and Tobago" },
      { code: "BZ", name: "Belize" },
      { code: "BS", name: "Bahamas" },
      { code: "BB", name: "Barbados" },
      { code: "AG", name: "Antigua and Barbuda" },
      { code: "DM", name: "Dominica" },
      { code: "GD", name: "Grenada" },
      { code: "KN", name: "Saint Kitts and Nevis" },
      { code: "LC", name: "Saint Lucia" },
      { code: "VC", name: "Saint Vincent and the Grenadines" },
    ],
  },
  {
    continent: "South America",
    countries: [
      { code: "BR", name: "Brazil" },
      { code: "AR", name: "Argentina" },
      { code: "CO", name: "Colombia" },
      { code: "PE", name: "Peru" },
      { code: "VE", name: "Venezuela" },
      { code: "CL", name: "Chile" },
      { code: "EC", name: "Ecuador" },
      { code: "BO", name: "Bolivia" },
      { code: "PY", name: "Paraguay" },
      { code: "UY", name: "Uruguay" },
      { code: "GY", name: "Guyana" },
      { code: "SR", name: "Suriname" },
    ],
  },
  {
    continent: "Europe",
    countries: [
      { code: "GB", name: "United Kingdom" },
      { code: "DE", name: "Germany" },
      { code: "FR", name: "France" },
      { code: "IT", name: "Italy" },
      { code: "ES", name: "Spain" },
      { code: "NL", name: "Netherlands" },
      { code: "BE", name: "Belgium" },
      { code: "AT", name: "Austria" },
      { code: "CH", name: "Switzerland" },
      { code: "PL", name: "Poland" },
      { code: "SE", name: "Sweden" },
      { code: "NO", name: "Norway" },
      { code: "DK", name: "Denmark" },
      { code: "FI", name: "Finland" },
      { code: "IE", name: "Ireland" },
      { code: "PT", name: "Portugal" },
      { code: "CZ", name: "Czech Republic" },
      { code: "RO", name: "Romania" },
      { code: "HU", name: "Hungary" },
      { code: "GR", name: "Greece" },
      { code: "BG", name: "Bulgaria" },
      { code: "HR", name: "Croatia" },
      { code: "SK", name: "Slovakia" },
      { code: "RS", name: "Serbia" },
      { code: "UA", name: "Ukraine" },
      { code: "LT", name: "Lithuania" },
      { code: "LV", name: "Latvia" },
      { code: "EE", name: "Estonia" },
      { code: "SI", name: "Slovenia" },
      { code: "LU", name: "Luxembourg" },
      { code: "MT", name: "Malta" },
      { code: "CY", name: "Cyprus" },
      { code: "IS", name: "Iceland" },
      { code: "LI", name: "Liechtenstein" },
      { code: "AL", name: "Albania" },
      { code: "MK", name: "North Macedonia" },
      { code: "ME", name: "Montenegro" },
      { code: "BA", name: "Bosnia and Herzegovina" },
      { code: "BY", name: "Belarus" },
      { code: "MD", name: "Moldova" },
      { code: "RU", name: "Russia" },
      { code: "TR", name: "Turkey" },
    ],
  },
  {
    continent: "Africa",
    countries: [
      { code: "ZA", name: "South Africa" },
      { code: "EG", name: "Egypt" },
      { code: "NG", name: "Nigeria" },
      { code: "KE", name: "Kenya" },
      { code: "MA", name: "Morocco" },
      { code: "GH", name: "Ghana" },
      { code: "TZ", name: "Tanzania" },
      { code: "ET", name: "Ethiopia" },
      { code: "TN", name: "Tunisia" },
      { code: "DZ", name: "Algeria" },
      { code: "CI", name: "Ivory Coast" },
      { code: "SN", name: "Senegal" },
      { code: "CM", name: "Cameroon" },
      { code: "UG", name: "Uganda" },
      { code: "ZW", name: "Zimbabwe" },
      { code: "LY", name: "Libya" },
      { code: "MU", name: "Mauritius" },
      { code: "BW", name: "Botswana" },
      { code: "NA", name: "Namibia" },
    ],
  },
  {
    continent: "Asia",
    countries: [
      { code: "CN", name: "China" },
      { code: "JP", name: "Japan" },
      { code: "IN", name: "India" },
      { code: "KR", name: "South Korea" },
      { code: "ID", name: "Indonesia" },
      { code: "TH", name: "Thailand" },
      { code: "VN", name: "Vietnam" },
      { code: "MY", name: "Malaysia" },
      { code: "SG", name: "Singapore" },
      { code: "PH", name: "Philippines" },
      { code: "HK", name: "Hong Kong" },
      { code: "TW", name: "Taiwan" },
      { code: "AE", name: "United Arab Emirates" },
      { code: "SA", name: "Saudi Arabia" },
      { code: "IL", name: "Israel" },
      { code: "PK", name: "Pakistan" },
      { code: "BD", name: "Bangladesh" },
      { code: "LK", name: "Sri Lanka" },
      { code: "QA", name: "Qatar" },
      { code: "KW", name: "Kuwait" },
      { code: "BH", name: "Bahrain" },
      { code: "OM", name: "Oman" },
      { code: "JO", name: "Jordan" },
      { code: "LB", name: "Lebanon" },
      { code: "PS", name: "Palestine" },
      { code: "IR", name: "Iran" },
      { code: "KP", name: "North Korea" },
      { code: "KZ", name: "Kazakhstan" },
      { code: "UZ", name: "Uzbekistan" },
      { code: "GE", name: "Georgia" },
      { code: "AZ", name: "Azerbaijan" },
      { code: "AM", name: "Armenia" },
    ],
  },
  {
    continent: "Oceania",
    countries: [
      { code: "AU", name: "Australia" },
      { code: "NZ", name: "New Zealand" },
      { code: "FJ", name: "Fiji" },
      { code: "PG", name: "Papua New Guinea" },
      { code: "WS", name: "Samoa" },
      { code: "TO", name: "Tonga" },
      { code: "SB", name: "Solomon Islands" },
      { code: "VU", name: "Vanuatu" },
    ],
  },
];

/** All country codes in a flat set for quick lookup. */
export const ALL_COUNTRY_CODES = new Set(
  COUNTRIES_BY_CONTINENT.flatMap((c) => c.countries.map((x) => x.code)),
);

/** All country names for "Country of origin" dropdown (empty first, then A–Z, then "Other"). */
export const COUNTRY_ORIGIN_OPTIONS: string[] = [
  "",
  ...COUNTRIES_BY_CONTINENT.flatMap((c) => c.countries.map((x) => x.name)).sort(
    (a, b) => a.localeCompare(b),
  ),
  "Other",
];
